### ISSUE TITLE
errors generated by Drupal during advagg tests

### ISSUE THREAD

**Issue by jshimota01** [maartentibau/moonocolor#6]
There is an extra comma in 5 files of the css.  I have repaired the files incase you ever wish to bundle.

[moono_color_errorsfixed.zip](https://github.com/maartentibau/moonocolor/files/5974804/moono_color_errorsfixed.zip)

**Comment by maartentibau** [comment]
Please file a PR if possible and I'll merge it.
I'm not really maintaining this repo anymore

**Comment by jshimota01** [comment]
sorry! I'm new here. a PR is a Pull Request or a Problem Report? Either way - I realize this project is a bit ancient.  I was cleaning errors and found a comma in a specific line of 5 files that generates an error - cleaned the files and uploaded them for someday being rolled up!  I won't trouble you further with this :)

**Comment by maartentibau** [comment]
@jshimota01 a PR is a Pull Request 😄 

I have added the files you've sent to the repository. Thx for the effort! 👍
